- name: Gather information about EC2 instances
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Fetch EC2 instance details
      amazon.aws.ec2_instance_info:
        region: us-east-1
        filters:
          "tag:aws:autoscaling:groupName": "app-stack*"
      register: ec2_instances_info

    - name: Print EC2 instance information
      debug:
        var: ec2_instances_info
    - name: Create a list of ASG instance IPs
      set_fact:
        asg_instance_ips: "{{ asg_instance_ips | default([]) + [item.network_interfaces[0].private_ip_address | default('')] }}"
      loop: "{{ ec2_instances_info.instances }}"
    - name: Remove Empty Values
      set_fact:
        asg_instance_ips: "{{ asg_instance_ips | reject('equalto', '') | list }}"
    - name: print ips
      debug:
        var: asg_instance_ips
    - name: login to docker hub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        docker_host: "tcp://{{ item }}:2375"
      loop: "{{ asg_instance_ips }}"
    - name: Finer container restart/update control
      community.docker.docker_container:
        docker_host: "tcp://{{ item }}:2375"
        name: json-api
        image: "{{ docker_image }}:{{ docker_tag }}"
        comparisons:
          image: ignore
          env: allow_more_present
          volumes: allow_more_present
      loop: "{{ asg_instance_ips }}"