name: Create containers

on:
  push:
    paths:
      - 'src/**'
      - 'dockerfile'
  pull_request:
    paths:
      - 'src/**'
      - 'dockerfile'
  create:
    tags:
  
jobs:
  build_n_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASS }}
      
      - name: Build and push Docker images with tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker build -t ${{ secrets.DOCKERUSER }}/json-api:${{ github.event.ref }} -f .
          docker tag ${{ secrets.DOCKERUSER }}/json-api:${{ github.event.ref }} ${{ secrets.DOCKERUSER }}/json-api:latest
          docker push ${{ secrets.DOCKERUSER }}/api:${{ github.event.ref }}
          docker push ${{ secrets.DOCKERUSER }}/api:latest
      
      - name: Build and push Docker images with PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${{ secrets.DOCKERUSER }}/json-api:dev-${{ github.event.pull_request.number }}-$SHORT_SHA .
          docker push ${{ secrets.DOCKERUSER }}/json-api:dev-${{ github.event.pull_request.number }}-$SHORT_SHA